-- ============================================================
--  うさぎ銀行 勘定系 スキーマ定義 (Oracle 11g 向け)
--  作成: 2014/03  システム部 勘定系G
-- ============================================================

CREATE SEQUENCE SEQ_CUSTOMER    START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ACCOUNT     START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRANSACTION START WITH 1    INCREMENT BY 1;

-- 店舗マスタ
CREATE TABLE BRANCH (
    BRANCH_CODE       VARCHAR2(3)    NOT NULL,
    BRANCH_NAME       VARCHAR2(40)   NOT NULL,
    BRANCH_NAME_KANA  VARCHAR2(40)   NOT NULL,
    CONSTRAINT PK_BRANCH PRIMARY KEY (BRANCH_CODE)
);

-- 顧客 (CIF)
CREATE TABLE CUSTOMER (
    CUSTOMER_ID   NUMBER(19)     NOT NULL,
    CIF_NO        VARCHAR2(10)   NOT NULL,
    NAME_KANJI    VARCHAR2(60)   NOT NULL,
    NAME_KANA     VARCHAR2(60)   NOT NULL,
    BIRTH_DATE    DATE           NOT NULL,
    POSTAL_CODE   VARCHAR2(8),
    ADDRESS       VARCHAR2(200),
    PHONE         VARCHAR2(15),
    KYC_STATUS    VARCHAR2(10)   DEFAULT 'PENDING' NOT NULL,
    CREATED_AT    TIMESTAMP      DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UK_CUSTOMER_CIF UNIQUE (CIF_NO),
    CONSTRAINT CK_CUSTOMER_KYC CHECK (KYC_STATUS IN ('PENDING', 'VERIFIED', 'REJECTED'))
);

-- 預金口座
CREATE TABLE ACCOUNT (
    ACCOUNT_ID        NUMBER(19)     NOT NULL,
    BRANCH_CODE       VARCHAR2(3)    NOT NULL,
    ACCOUNT_NO        VARCHAR2(7)    NOT NULL,
    ACCOUNT_TYPE      VARCHAR2(12)   NOT NULL,
    STATUS            VARCHAR2(10)   DEFAULT 'ACTIVE' NOT NULL,
    CUSTOMER_ID       NUMBER(19)     NOT NULL,
    BALANCE           NUMBER(15)     DEFAULT 0 NOT NULL,
    INTEREST_RATE     NUMBER(7,4)    DEFAULT 0.0010 NOT NULL,
    ACCRUED_INTEREST  NUMBER(17,2)   DEFAULT 0 NOT NULL,
    OPENED_ON         DATE           NOT NULL,
    LAST_TXN_ON       DATE,
    VERSION_NO        NUMBER(19)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT UK_ACCOUNT_NO UNIQUE (BRANCH_CODE, ACCOUNT_NO),
    CONSTRAINT FK_ACCOUNT_BRANCH FOREIGN KEY (BRANCH_CODE) REFERENCES BRANCH (BRANCH_CODE),
    CONSTRAINT FK_ACCOUNT_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
    CONSTRAINT CK_ACCOUNT_TYPE CHECK (ACCOUNT_TYPE IN ('ORDINARY', 'CURRENT', 'SAVINGS', 'TIME_DEPOSIT')),
    CONSTRAINT CK_ACCOUNT_STATUS CHECK (STATUS IN ('ACTIVE', 'FROZEN', 'DORMANT', 'CLOSED')),
    CONSTRAINT CK_ACCOUNT_BALANCE CHECK (BALANCE >= 0)
);

CREATE INDEX IX_ACCOUNT_CUSTOMER ON ACCOUNT (CUSTOMER_ID);
CREATE INDEX IX_ACCOUNT_STATUS   ON ACCOUNT (STATUS, BRANCH_CODE);

-- 取引明細 (元帳)
CREATE TABLE TRANSACTION (
    TRANSACTION_ID  NUMBER(19)     NOT NULL,
    ACCOUNT_ID      NUMBER(19)     NOT NULL,
    TXN_TYPE        VARCHAR2(15)   NOT NULL,
    AMOUNT          NUMBER(15)     NOT NULL,
    BALANCE_AFTER   NUMBER(15)     NOT NULL,
    DESCRIPTION     VARCHAR2(100),
    REFERENCE_NO    VARCHAR2(20),
    VALUE_DATE      DATE           NOT NULL,
    POSTED_AT       TIMESTAMP      DEFAULT SYSDATE NOT NULL,
    OPERATOR_ID     VARCHAR2(30),
    CONSTRAINT PK_TRANSACTION PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT FK_TXN_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID),
    CONSTRAINT CK_TXN_AMOUNT CHECK (AMOUNT > 0)
);

CREATE INDEX IX_TXN_ACCOUNT_DATE ON TRANSACTION (ACCOUNT_ID, VALUE_DATE);
CREATE INDEX IX_TXN_REFERENCE    ON TRANSACTION (REFERENCE_NO);
